CREATE TABLE IF NOT EXISTS {{talbe_name}}
(

    --     Для почти всех полей я использую TEXT т.к. документация содержит неточности и нет гарантий, что длины полей
    --     такие, какие указаны. Поэтому во избежание ошибок - TEXT

    id                        BIGSERIAL PRIMARY KEY,
    last_update_from          DATE,
    last_update_to            DATE,

    info_reg_num                   TEXT,
    info_code                      TEXT,
    info_division_parent_name      TEXT,
    info_division_parent_code      TEXT,
    info_dsp                       TEXT,
    info_ogrn                      TEXT,
    info_full_name                 TEXT,
    info_short_name                TEXT,
    info_inn                       TEXT,
    info_kpp                       TEXT,

    info_spec_event_code           TEXT,
    info_spec_event_code_dop1      TEXT,
    info_spec_event_code_dop2      TEXT,
    info_spec_event_code_dop3      TEXT,

    info_reg_date                  TIMESTAMP,

    info_okopf_name                TEXT,
    info_okopf_code                TEXT,
    info_refokopf_code             TEXT,
    info_okfs_name                 TEXT,
    info_okfs_code                 TEXT,
    info_refokfs_code              TEXT,
    info_post_index                TEXT,
    info_region_kladr_code         TEXT,
    info_region_code               TEXT,
    info_region_type               TEXT,
    info_region_name               TEXT,

    info_planning_structure_type   TEXT,
    info_planning_structure_name   TEXT,

    info_area_code                 TEXT,
    info_area_type                 TEXT,
    info_area_name                 TEXT,
    info_city_code                 TEXT,
    info_city_type                 TEXT,
    info_city_name                 TEXT,
    info_local_code                TEXT,
    info_local_type                TEXT,
    info_local_name                TEXT,
    info_street_code               TEXT,
    info_street_type               TEXT,
    info_street_name               TEXT,
    info_house                     TEXT,
    info_building                  TEXT,
    info_apartment                 TEXT,

    info_oktmo_code                TEXT,
    info_oktmo_name                TEXT,
    info_orfk_name                 TEXT,
    info_orfk_code                 TEXT,
    info_reforfk_code              TEXT,
    info_oksm_name                 TEXT,
    info_oksm_code                 TEXT,
    info_location                  TEXT,
    info_kbk_code                  TEXT,
    info_kbk_name                  TEXT,

    info_okogu_code                TEXT,
    info_refokogu_code             TEXT,
    info_okogu_name                TEXT,
    info_okpo_code                 TEXT,
    info_org_type_code             TEXT,
    info_org_type_name             TEXT,
    info_establishment_kind_code   TEXT,
    info_establishment_kind_name   TEXT,
    info_legal_person_kind_code    TEXT,
    info_legal_person_kind_name    TEXT,
    info_ougv_name                 TEXT,
    info_ougv_code                 TEXT,
    info_uo_code                   TEXT,
    info_uo_name                   TEXT,

    info_creator_kind_name         TEXT,
    info_creator_kind_code         TEXT,
    info_creator_place_name        TEXT,
    info_creator_place_code        TEXT,
    info_founder_kind_name         TEXT,
    info_founder_kind_code         TEXT,
    info_founder_place_name        TEXT,
    info_founder_place_code        TEXT,
    info_budget_lvl_name           TEXT,
    info_budget_lvl_code           TEXT,
    info_budget_name               TEXT,
    info_budget_code               TEXT,
    info_status_code               TEXT,
    info_status_name               TEXT,

    info_naib_znach_uch            BOOLEAN,
    info_is_ogv                    BOOLEAN,
    info_is_uch                    TEXT,
    info_is_obosob                 BOOLEAN,
    info_is_excluded               BOOLEAN,
    info_is_reorg                  BOOLEAN,
    info_org_status                TEXT,
    info_parent_code               TEXT,
    info_parent_name               TEXT,
    info_firm_name                 TEXT,
    info_kofk_code                 TEXT,
    info_refkofk_code              TEXT,
    info_name_docs                 TEXT,
    info_okato_code                TEXT,
    info_okato_name                TEXT,

    info_guid                      TEXT,
    info_start_date                TIMESTAMP,
    info_end_date                  TIMESTAMP,
    info_status                    TEXT,
    info_record_num                TEXT,
    info_control_num               TEXT,
    info_bid_num                   TEXT,
    info_first_reg_guid            TEXT,
    info_first_reg_date            TIMESTAMP,

    info_last_reg_num              TEXT,
    info_last_reg_guid             TEXT,
    info_last_reg_date             TIMESTAMP,

    info_update_reason             TEXT,
    info_update_num                INTEGER,
    info_acc_mgmt                  TEXT,
    info_inclusion_date            TIMESTAMP,
    info_exclusion_date            TIMESTAMP,

    info_pubp_code                 TEXT,
    info_rubp_code                 TEXT,
    info_nubp_code                 TEXT,
    info_cpz_code                  TEXT,
    info_pgmy_code                 TEXT,

    info_parent_record_num         TEXT,
    info_reformation_document      TEXT,
    info_reformation_document_num  TEXT,
    info_reformation_document_date DATE,
    info_reformation_name          TEXT,
    info_reformation_code          TEXT,
    info_reformation_start_date    DATE,
    info_reformation_end_date      DATE,
    info_contour_type_code         TEXT,
    info_load_date                 DATE,
    info_date_update               DATE,
    info_egrul_not_included        TEXT,
    info_ppotypecode               TEXT,
    info_ppotypename               TEXT
);
