CREATE TABLE IF NOT EXISTS e_budget
(
    id
    BIGSERIAL
    PRIMARY
    KEY,
    last_update_from
    DATE,
    last_update_to
    DATE,

    info_reg_num
    TEXT,
    info_code
    TEXT,
    info_division_parent_name
    TEXT,
    info_division_parent_code
    TEXT,
    info_dsp
    TEXT,
    info_ogrn
    TEXT,
    info_full_name
    TEXT,
    info_short_name
    TEXT,
    info_inn
    TEXT,
    info_kpp
    TEXT,

    info_spec_event_code
    TEXT,
    info_spec_event_code_dop1
    TEXT,
    info_spec_event_code_dop2
    TEXT,
    info_spec_event_code_dop3
    TEXT,

    info_reg_date
    TIMESTAMP,

    info_okopf_name
    TEXT,
    info_okopf_code
    TEXT,
    info_refokopf_code
    TEXT,
    info_okfs_name
    TEXT,
    info_okfs_code
    TEXT,
    info_refokfs_code
    TEXT,
    info_post_index
    TEXT,
    info_region_kladr_code
    TEXT,
    info_region_code
    TEXT,
    info_region_type
    TEXT,
    info_region_name
    TEXT,

    info_planning_structure_type
    TEXT,
    info_planning_structure_name
    TEXT,

    info_area_code
    TEXT,
    info_area_type
    TEXT,
    info_area_name
    TEXT,
    info_city_code
    TEXT,
    info_city_type
    TEXT,
    info_city_name
    TEXT,
    info_local_code
    TEXT,
    info_local_type
    TEXT,
    info_local_name
    TEXT,
    info_street_code
    TEXT,
    info_street_type
    TEXT,
    info_street_name
    TEXT,
    info_house
    TEXT,
    info_building
    TEXT,
    info_apartment
    TEXT,

    info_oktmo_code
    TEXT,
    info_oktmo_name
    TEXT,
    info_orfk_name
    TEXT,
    info_orfk_code
    TEXT,
    info_reforfk_code
    TEXT,
    info_oksm_name
    TEXT,
    info_oksm_code
    TEXT,
    info_location
    TEXT,
    info_kbk_code
    TEXT,
    info_kbk_name
    TEXT,

    info_okogu_code
    TEXT,
    info_refokogu_code
    TEXT,
    info_okogu_name
    TEXT,
    info_okpo_code
    TEXT,
    info_org_type_code
    TEXT,
    info_org_type_name
    TEXT,
    info_establishment_kind_code
    TEXT,
    info_establishment_kind_name
    TEXT,
    info_legal_person_kind_code
    TEXT,
    info_legal_person_kind_name
    TEXT,
    info_ougv_name
    TEXT,
    info_ougv_code
    TEXT,
    info_uo_code
    TEXT,
    info_uo_name
    TEXT,

    info_creator_kind_name
    TEXT,
    info_creator_kind_code
    TEXT,
    info_creator_place_name
    TEXT,
    info_creator_place_code
    TEXT,
    info_founder_kind_name
    TEXT,
    info_founder_kind_code
    TEXT,
    info_founder_place_name
    TEXT,
    info_founder_place_code
    TEXT,
    info_budget_lvl_name
    TEXT,
    info_budget_lvl_code
    TEXT,
    info_budget_name
    TEXT,
    info_budget_code
    TEXT,
    info_status_code
    TEXT,
    info_status_name
    TEXT,

    info_naib_znach_uch
    BOOLEAN,
    info_is_ogv
    BOOLEAN,
    info_is_uch
    TEXT,
    info_is_obosob
    BOOLEAN,
    info_is_excluded
    BOOLEAN,
    info_is_reorg
    BOOLEAN,
    info_org_status
    TEXT,
    info_parent_code
    TEXT,
    info_parent_name
    TEXT,
    info_firm_name
    TEXT,
    info_kofk_code
    TEXT,
    info_refkofk_code
    TEXT,
    info_name_docs
    TEXT,
    info_okato_code
    TEXT,
    info_okato_name
    TEXT,

    info_guid
    TEXT
    NOT
    NULL
    UNIQUE,
    info_start_date
    TIMESTAMP,
    info_end_date
    TIMESTAMP,
    info_status
    TEXT,
    info_record_num
    TEXT,
    info_control_num
    TEXT,
    info_bid_num
    TEXT,
    info_first_reg_guid
    TEXT,
    info_first_reg_date
    TIMESTAMP,

    info_last_reg_num
    TEXT,
    info_last_reg_guid
    TEXT,
    info_last_reg_date
    TIMESTAMP,

    info_update_reason
    TEXT,
    info_update_num
    INTEGER,
    info_acc_mgmt
    TEXT,
    info_inclusion_date
    TIMESTAMP,
    info_exclusion_date
    TIMESTAMP,

    info_pubp_code
    TEXT,
    info_rubp_code
    TEXT,
    info_nubp_code
    TEXT,
    info_cpz_code
    TEXT,
    info_pgmy_code
    TEXT,

    info_parent_record_num
    TEXT,
    info_reformation_document
    TEXT,
    info_reformation_document_num
    TEXT,
    info_reformation_document_date
    DATE,
    info_reformation_name
    TEXT,
    info_reformation_code
    TEXT,
    info_reformation_start_date
    DATE,
    info_reformation_end_date
    DATE,
    info_contour_type_code
    TEXT,
    info_load_date
    DATE,
    info_date_update
    DATE,
    info_egrul_not_included
    TEXT,
    info_ppotypecode
    TEXT,
    info_ppotypename
    TEXT,


    accept_auths_code
    TEXT,
    accept_auths_name
    TEXT,
    accept_auths_start_date
    TEXT,
    accept_auths_end_date
    TEXT,
    accept_auths_auth_budg_code
    TEXT,
    accept_auths_auth_budg_name
    TEXT,
    accept_auths_auth_ppo_code
    TEXT,
    accept_auths_auth_ppo_name
    TEXT,
    accept_auths_auth_kbk_glava_code
    TEXT,
    accept_auths_auth_kbk_glava_name
    TEXT,
    accept_auths_auth_giver_code
    TEXT,
    accept_auths_auth_giver_name
    TEXT,
    accept_auths_user_area
    TEXT,
    accept_auths_auth_reg_num
    TEXT,

    activities_activity_code
    TEXT,
    activities_ref_activity_code
    TEXT,
    activities_activity_name
    TEXT,
    activities_activity_kind
    TEXT,

    authorities_authority_code
    TEXT,
    authorities_authority_name
    TEXT,

    authorities_permissions_permission_code
    TEXT,
    authorities_permissions_permission_name
    TEXT,

    contacts_phone
    TEXT,
    contacts_site
    TEXT,
    contacts_mail
    TEXT,

    contracts_contract_number
    TEXT,
    contracts_sign_date
    TEXT,
    contracts_org_code_contract
    TEXT,
    contracts_org_name_contract
    TEXT,
    contracts_orgcontractbudgetcode
    TEXT,

    fo_accounts_fo_name
    TEXT,
    fo_accounts_fo_code
    TEXT,
    fo_accounts_account_type_name
    TEXT,
    fo_accounts_num
    TEXT,

    facial_accounts_srv_ufk_code
    TEXT,
    facial_accounts_ref_srv_ufk_code
    TEXT,
    facial_accounts_srv_ufk_name
    TEXT,
    facial_accounts_open_tofk_code
    TEXT,
    facial_accounts_open_tofk_name
    TEXT,
    facial_accounts_open_ufk_code
    TEXT,
    facial_accounts_ref_open_ufk_code
    TEXT,
    facial_accounts_open_ufk_name
    TEXT,
    facial_accounts_kind_name
    TEXT,
    facial_accounts_kind_code
    TEXT,
    facial_accounts_status
    TEXT,
    facial_accounts_num
    TEXT,
    facial_accounts_close_date
    TEXT,
    facial_accounts_create_date
    TEXT,
    facial_accounts_account_org_code
    TEXT,
    facial_accounts_account_org_full_name
    TEXT,
    facial_accounts_ppo_code
    TEXT,
    facial_accounts_ppo_name
    TEXT,

    heads_fio
    TEXT,
    heads_post
    TEXT,
    heads_head_main
    TEXT,
    heads_doc_name
    TEXT,
    heads_doc_num
    TEXT,
    heads_doc_date
    TEXT,

    ks_accounts_num
    TEXT,
    ks_accounts_open_date
    TEXT,
    ks_accounts_close_date
    TEXT,
    ks_accounts_open_tofk_code
    TEXT,
    ks_accounts_open_tofk_name
    TEXT,
    ks_accounts_ref_srv_ufk_code
    TEXT,
    ks_accounts_account_vid_name
    TEXT,
    ks_accounts_ppo_code
    TEXT,

    non_participant_permissions_code
    TEXT,
    non_participant_permissions_name
    TEXT,
    non_participant_permissions_start_date
    TEXT,
    non_participant_permissions_end_date
    TEXT,
    non_participant_permissions_auth_budg_code
    TEXT,
    non_participant_permissions_auth_budg_name
    TEXT,
    non_participant_permissions_auth_ppo_code
    TEXT,
    non_participant_permissions_auth_ppo_name
    TEXT,
    non_participant_permissions_auth_kbk_glava_code
    TEXT,
    non_participant_permissions_auth_kbk_glava_name
    TEXT,
    non_participant_permissions_registry_num
    TEXT,

    participant_permissions_code
    TEXT,
    participant_permissions_name
    TEXT,
    participant_permissions_start_date
    TEXT,
    participant_permissions_end_date
    TEXT,

    procurement_permissions_name
    TEXT,
    procurement_permissions_code
    TEXT,
    procurement_permissions_start_date
    TEXT,
    procurement_permissions_end_date
    TEXT,

    successions_parent_name
    TEXT,
    successions_parent_code
    TEXT,
    successions_ogrn
    TEXT,
    successions_doc_name
    TEXT,
    successions_number_doc
    TEXT,
    successions_document_date
    TEXT,
    successions_data_source
    TEXT,

    transf_auth_auth_fo_villages_ppo_name
    TEXT,
    transf_auth_auth_fo_villages_ppo_code
    TEXT,
    transf_auth_auth_fo_villages_code
    TEXT,
    transf_auth_auth_fo_villages_name
    TEXT,
    transf_auth_auth_fo_municipal_code
    TEXT,
    transf_auth_auth_fo_municipal_name
    TEXT,
    transf_auth_auth_reg_num
    TEXT,
    transf_auth_auth_start_date
    TEXT,
    transf_auth_auth_end_date
    TEXT,
    transf_auth_kbk_glava_code
    TEXT,
    transf_auth_budget_code
    TEXT,

    ubpfin_fin_doc_name
    TEXT,
    ubpfin_fin_doc_num
    TEXT,
    ubpfin_fin_doc_date
    TEXT,

    ubp_fin_fku_fku_doc_name
    TEXT,
    ubp_fin_fku_fku_doc_num
    TEXT,
    ubp_fin_fku_fku_doc_date
    TEXT,

    ubp_transf_auth_bp_ppo_name
    TEXT,
    ubp_transf_auth_bp_ppo_code
    TEXT,
    ubp_transf_auth_bp_bud_level_nsi_code
    TEXT,
    ubp_transf_auth_bp_bud_level_nsi_name
    TEXT,
    ubp_transf_auth_bp_budget_nsi_code
    TEXT,
    ubp_transf_auth_bp_budget_nsi_name
    TEXT,
    ubp_transf_auth_bp_code_bk
    TEXT,
    ubp_transf_auth_bp_head_name
    TEXT,

    ubp_transf_auth_bu_auth_bu_auth_org_code
    TEXT,
    ubp_transf_auth_bu_auth_bu_auth_name
    TEXT,
    ubp_transf_auth_bu_auth_bu_start_date
    TEXT,
    ubp_transf_auth_bu_auth_bu_end_date
    TEXT,

    updated_at
    TIMESTAMP NOT NULL DEFAULT NOW()

);

CREATE INDEX IF NOT EXISTS idx_e_budget_updated_at ON e_budget(updated_at);
