
CREATE TABLE IF NOT EXISTS e_budget
(
    last_update_from
        Date,
    last_update_to
        Date,

    info_reg_num
        String,
    info_code
        String,
    info_division_parent_name
        String,
    info_division_parent_code
        String,
    info_dsp
        String,
    info_ogrn
        String,
    info_full_name
        String,
    info_short_name
        String,
    info_inn
        String,
    info_kpp
        String,

    info_spec_event_code
        String,
    info_spec_event_code_dop1
        String,
    info_spec_event_code_dop2
        String,
    info_spec_event_code_dop3
        String,

    info_reg_date
        DateTime,

    info_okopf_name
        String,
    info_okopf_code
        String,
    info_refokopf_code
        String,
    info_okfs_name
        String,
    info_okfs_code
        String,
    info_refokfs_code
        String,
    info_post_index
        String,
    info_region_kladr_code
        String,
    info_region_code
        String,
    info_region_type
        String,
    info_region_name
        String,

    info_planning_structure_type
        String,
    info_planning_structure_name
        String,

    info_area_code
        String,
    info_area_type
        String,
    info_area_name
        String,
    info_city_code
        String,
    info_city_type
        String,
    info_city_name
        String,
    info_local_code
        String,
    info_local_type
        String,
    info_local_name
        String,
    info_street_code
        String,
    info_street_type
        String,
    info_street_name
        String,
    info_house
        String,
    info_building
        String,
    info_apartment
        String,

    info_oktmo_code
        String,
    info_oktmo_name
        String,
    info_orfk_name
        String,
    info_orfk_code
        String,
    info_reforfk_code
        String,
    info_oksm_name
        String,
    info_oksm_code
        String,
    info_location
        String,
    info_kbk_code
        String,
    info_kbk_name
        String,

    info_okogu_code
        String,
    info_refokogu_code
        String,
    info_okogu_name
        String,
    info_okpo_code
        String,
    info_org_type_code
        String,
    info_org_type_name
        String,
    info_establishment_kind_code
        String,
    info_establishment_kind_name
        String,
    info_legal_person_kind_code
        String,
    info_legal_person_kind_name
        String,
    info_ougv_name
        String,
    info_ougv_code
        String,
    info_uo_code
        String,
    info_uo_name
        String,

    info_creator_kind_name
        String,
    info_creator_kind_code
        String,
    info_creator_place_name
        String,
    info_creator_place_code
        String,
    info_founder_kind_name
        String,
    info_founder_kind_code
        String,
    info_founder_place_name
        String,
    info_founder_place_code
        String,
    info_budget_lvl_name
        String,
    info_budget_lvl_code
        String,
    info_budget_name
        String,
    info_budget_code
        String,
    info_status_code
        String,
    info_status_name
        String,

    info_naib_znach_uch
        Bool,
    info_is_ogv
        Bool,
    info_is_uch
        String,
    info_is_obosob
        Bool,
    info_is_excluded
        Bool,
    info_is_reorg
        Bool,
    info_org_status
        String,
    info_parent_code
        String,
    info_parent_name
        String,
    info_firm_name
        String,
    info_kofk_code
        String,
    info_refkofk_code
        String,
    info_name_docs
        String,
    info_okato_code
        String,
    info_okato_name
        String,

    info_guid
        String,
    info_start_date
        DateTime,
    info_end_date
        DateTime,
    info_status
        String,
    info_record_num
        String,
    info_control_num
        String,
    info_bid_num
        String,
    info_first_reg_guid
        String,
    info_first_reg_date
        DateTime,

    info_last_reg_num
        String,
    info_last_reg_guid
        String,
    info_last_reg_date
        DateTime,

    info_update_reason
        String,
    info_update_num
        Int32,
    info_acc_mgmt
        String,
    info_inclusion_date
        DateTime,
    info_exclusion_date
        DateTime,

    info_pubp_code
        String,
    info_rubp_code
        String,
    info_nubp_code
        String,
    info_cpz_code
        String,
    info_pgmy_code
        String,

    info_parent_record_num
        String,
    info_reformation_document
        String,
    info_reformation_document_num
        String,
    info_reformation_document_date
        Date,
    info_reformation_name
        String,
    info_reformation_code
        String,
    info_reformation_start_date
        Date,
    info_reformation_end_date
        Date,
    info_contour_type_code
        String,
    info_load_date
        Date,
    info_date_update
        Date,
    info_egrul_not_included
        String,
    info_ppotypecode
        String,
    info_ppotypename
        String,


    accept_auths_code
        String,
    accept_auths_name
        String,
    accept_auths_start_date
        String,
    accept_auths_end_date
        String,
    accept_auths_auth_budg_code
        String,
    accept_auths_auth_budg_name
        String,
    accept_auths_auth_ppo_code
        String,
    accept_auths_auth_ppo_name
        String,
    accept_auths_auth_kbk_glava_code
        String,
    accept_auths_auth_kbk_glava_name
        String,
    accept_auths_auth_giver_code
        String,
    accept_auths_auth_giver_name
        String,
    accept_auths_user_area
        String,
    accept_auths_auth_reg_num
        String,

    activities_activity_code
        String,
    activities_ref_activity_code
        String,
    activities_activity_name
        String,
    activities_activity_kind
        String,

    authorities_authority_code
        String,
    authorities_authority_name
        String,

    authorities_permissions_permission_code
        String,
    authorities_permissions_permission_name
        String,

    contacts_phone
        String,
    contacts_site
        String,
    contacts_mail
        String,

    contracts_contract_number
        String,
    contracts_sign_date
        String,
    contracts_org_code_contract
        String,
    contracts_org_name_contract
        String,
    contracts_orgcontractbudgetcode
        String,

    fo_accounts_fo_name
        String,
    fo_accounts_fo_code
        String,
    fo_accounts_account_type_name
        String,
    fo_accounts_num
        String,

    facial_accounts_srv_ufk_code
        String,
    facial_accounts_ref_srv_ufk_code
        String,
    facial_accounts_srv_ufk_name
        String,
    facial_accounts_open_tofk_code
        String,
    facial_accounts_open_tofk_name
        String,
    facial_accounts_open_ufk_code
        String,
    facial_accounts_ref_open_ufk_code
        String,
    facial_accounts_open_ufk_name
        String,
    facial_accounts_kind_name
        String,
    facial_accounts_kind_code
        String,
    facial_accounts_status
        String,
    facial_accounts_num
        String,
    facial_accounts_close_date
        String,
    facial_accounts_create_date
        String,
    facial_accounts_account_org_code
        String,
    facial_accounts_account_org_full_name
        String,
    facial_accounts_ppo_code
        String,
    facial_accounts_ppo_name
        String,

    heads_fio
        String,
    heads_post
        String,
    heads_head_main
        String,
    heads_doc_name
        String,
    heads_doc_num
        String,
    heads_doc_date
        String,

    ks_accounts_num
        String,
    ks_accounts_open_date
        String,
    ks_accounts_close_date
        String,
    ks_accounts_open_tofk_code
        String,
    ks_accounts_open_tofk_name
        String,
    ks_accounts_ref_srv_ufk_code
        String,
    ks_accounts_account_vid_name
        String,
    ks_accounts_ppo_code
        String,

    non_participant_permissions_code
        String,
    non_participant_permissions_name
        String,
    non_participant_permissions_start_date
        String,
    non_participant_permissions_end_date
        String,
    non_participant_permissions_auth_budg_code
        String,
    non_participant_permissions_auth_budg_name
        String,
    non_participant_permissions_auth_ppo_code
        String,
    non_participant_permissions_auth_ppo_name
        String,
    non_participant_permissions_auth_kbk_glava_code
        String,
    non_participant_permissions_auth_kbk_glava_name
        String,
    non_participant_permissions_registry_num
        String,

    participant_permissions_code
        String,
    participant_permissions_name
        String,
    participant_permissions_start_date
        String,
    participant_permissions_end_date
        String,

    procurement_permissions_name
        String,
    procurement_permissions_code
        String,
    procurement_permissions_start_date
        String,
    procurement_permissions_end_date
        String,

    successions_parent_name
        String,
    successions_parent_code
        String,
    successions_ogrn
        String,
    successions_doc_name
        String,
    successions_number_doc
        String,
    successions_document_date
        String,
    successions_data_source
        String,

    transf_auth_auth_fo_villages_ppo_name
        String,
    transf_auth_auth_fo_villages_ppo_code
        String,
    transf_auth_auth_fo_villages_code
        String,
    transf_auth_auth_fo_villages_name
        String,
    transf_auth_auth_fo_municipal_code
        String,
    transf_auth_auth_fo_municipal_name
        String,
    transf_auth_auth_reg_num
        String,
    transf_auth_auth_start_date
        String,
    transf_auth_auth_end_date
        String,
    transf_auth_kbk_glava_code
        String,
    transf_auth_budget_code
        String,

    ubpfin_fin_doc_name
        String,
    ubpfin_fin_doc_num
        String,
    ubpfin_fin_doc_date
        String,

    ubp_fin_fku_fku_doc_name
        String,
    ubp_fin_fku_fku_doc_num
        String,
    ubp_fin_fku_fku_doc_date
        String,

    ubp_transf_auth_bp_ppo_name
        String,
    ubp_transf_auth_bp_ppo_code
        String,
    ubp_transf_auth_bp_bud_level_nsi_code
        String,
    ubp_transf_auth_bp_bud_level_nsi_name
        String,
    ubp_transf_auth_bp_budget_nsi_code
        String,
    ubp_transf_auth_bp_budget_nsi_name
        String,
    ubp_transf_auth_bp_code_bk
        String,
    ubp_transf_auth_bp_head_name
        String,

    ubp_transf_auth_bu_auth_bu_auth_org_code
        String,
    ubp_transf_auth_bu_auth_bu_auth_name
        String,
    ubp_transf_auth_bu_auth_bu_start_date
        String,
    ubp_transf_auth_bu_auth_bu_end_date
        String,

    updated_at
        DateTime
)
    ENGINE = ReplacingMergeTree(updated_at) ORDER BY (info_guid);
