
CREATE TABLE IF NOT EXISTS e_budget
(
    last_update_from
        Nullable(Date32),
    last_update_to
        Nullable(Date32),

    info_reg_num
        Nullable(String),
    info_code
        Nullable(String),
    info_division_parent_name
        Nullable(String),
    info_division_parent_code
        Nullable(String),
    info_dsp
        Nullable(String),
    info_ogrn
        Nullable(String),
    info_full_name
        Nullable(String),
    info_short_name
        Nullable(String),
    info_inn
        Nullable(String),
    info_kpp
        Nullable(String),

    info_spec_event_code
        Nullable(String),
    info_spec_event_code_dop1
        Nullable(String),
    info_spec_event_code_dop2
        Nullable(String),
    info_spec_event_code_dop3
        Nullable(String),

    info_reg_date
        Nullable(DateTime),

    info_okopf_name
        Nullable(String),
    info_okopf_code
        Nullable(String),
    info_refokopf_code
        Nullable(String),
    info_okfs_name
        Nullable(String),
    info_okfs_code
        Nullable(String),
    info_refokfs_code
        Nullable(String),
    info_post_index
        Nullable(String),
    info_region_kladr_code
        Nullable(String),
    info_region_code
        Nullable(String),
    info_region_type
        Nullable(String),
    info_region_name
        Nullable(String),

    info_planning_structure_type
        Nullable(String),
    info_planning_structure_name
        Nullable(String),

    info_area_code
        Nullable(String),
    info_area_type
        Nullable(String),
    info_area_name
        Nullable(String),
    info_city_code
        Nullable(String),
    info_city_type
        Nullable(String),
    info_city_name
        Nullable(String),
    info_local_code
        Nullable(String),
    info_local_type
        Nullable(String),
    info_local_name
        Nullable(String),
    info_street_code
        Nullable(String),
    info_street_type
        Nullable(String),
    info_street_name
        Nullable(String),
    info_house
        Nullable(String),
    info_building
        Nullable(String),
    info_apartment
        Nullable(String),

    info_oktmo_code
        Nullable(String),
    info_oktmo_name
        Nullable(String),
    info_orfk_name
        Nullable(String),
    info_orfk_code
        Nullable(String),
    info_reforfk_code
        Nullable(String),
    info_oksm_name
        Nullable(String),
    info_oksm_code
        Nullable(String),
    info_location
        Nullable(String),
    info_kbk_code
        Nullable(String),
    info_kbk_name
        Nullable(String),

    info_okogu_code
        Nullable(String),
    info_refokogu_code
        Nullable(String),
    info_okogu_name
        Nullable(String),
    info_okpo_code
        Nullable(String),
    info_org_type_code
        Nullable(String),
    info_org_type_name
        Nullable(String),
    info_establishment_kind_code
        Nullable(String),
    info_establishment_kind_name
        Nullable(String),
    info_legal_person_kind_code
        Nullable(String),
    info_legal_person_kind_name
        Nullable(String),
    info_ougv_name
        Nullable(String),
    info_ougv_code
        Nullable(String),
    info_uo_code
        Nullable(String),
    info_uo_name
        Nullable(String),

    info_creator_kind_name
        Nullable(String),
    info_creator_kind_code
        Nullable(String),
    info_creator_place_name
        Nullable(String),
    info_creator_place_code
        Nullable(String),
    info_founder_kind_name
        Nullable(String),
    info_founder_kind_code
        Nullable(String),
    info_founder_place_name
        Nullable(String),
    info_founder_place_code
        Nullable(String),
    info_budget_lvl_name
        Nullable(String),
    info_budget_lvl_code
        Nullable(String),
    info_budget_name
        Nullable(String),
    info_budget_code
        Nullable(String),
    info_status_code
        Nullable(String),
    info_status_name
        Nullable(String),

    info_naib_znach_uch
        Nullable(Bool),
    info_is_ogv
        Nullable(Bool),
    info_is_uch
        Nullable(String),
    info_is_obosob
        Nullable(Bool),
    info_is_excluded
        Nullable(Bool),
    info_is_reorg
        Nullable(Bool),
    info_org_status
        Nullable(String),
    info_parent_code
        Nullable(String),
    info_parent_name
        Nullable(String),
    info_firm_name
        Nullable(String),
    info_kofk_code
        Nullable(String),
    info_refkofk_code
        Nullable(String),
    info_name_docs
        Nullable(String),
    info_okato_code
        Nullable(String),
    info_okato_name
        Nullable(String),

    info_guid
        String,
    info_start_date
        Nullable(DateTime64),
    info_end_date
        Nullable(DateTime64),
    info_status
        Nullable(String),
    info_record_num
        Nullable(String),
    info_control_num
        Nullable(String),
    info_bid_num
        Nullable(String),
    info_first_reg_guid
        Nullable(String),
    info_first_reg_date
        Nullable(DateTime64),

    info_last_reg_num
        Nullable(String),
    info_last_reg_guid
        Nullable(String),
    info_last_reg_date
        Nullable(DateTime64),

    info_update_reason
        Nullable(String),
    info_update_num
        Nullable(Int32),
    info_acc_mgmt
        Nullable(String),
    info_inclusion_date
        Nullable(DateTime64),
    info_exclusion_date
        Nullable(DateTime64),

    info_pubp_code
        Nullable(String),
    info_rubp_code
        Nullable(String),
    info_nubp_code
        Nullable(String),
    info_cpz_code
        Nullable(String),
    info_pgmy_code
        Nullable(String),

    info_parent_record_num
        Nullable(String),
    info_reformation_document
        Nullable(String),
    info_reformation_document_num
        Nullable(String),
    info_reformation_document_date
        Nullable(Date32),
    info_reformation_name
        Nullable(String),
    info_reformation_code
        Nullable(String),
    info_reformation_start_date
        Nullable(Date32),
    info_reformation_end_date
        Nullable(Date32),
    info_contour_type_code
        Nullable(String),
    info_load_date
        Nullable(Date32),
    info_date_update
        Nullable(Date32),
    info_egrul_not_included
        Nullable(String),
    info_ppotypecode
        Nullable(String),
    info_ppotypename
        Nullable(String),


    accept_auths_code
        Nullable(String),
    accept_auths_name
        Nullable(String),
    accept_auths_start_date
        Nullable(String),
    accept_auths_end_date
        Nullable(String),
    accept_auths_auth_budg_code
        Nullable(String),
    accept_auths_auth_budg_name
        Nullable(String),
    accept_auths_auth_ppo_code
        Nullable(String),
    accept_auths_auth_ppo_name
        Nullable(String),
    accept_auths_auth_kbk_glava_code
        Nullable(String),
    accept_auths_auth_kbk_glava_name
        Nullable(String),
    accept_auths_auth_giver_code
        Nullable(String),
    accept_auths_auth_giver_name
        Nullable(String),
    accept_auths_user_area
        Nullable(String),
    accept_auths_auth_reg_num
        Nullable(String),

    activities_activity_code
        Nullable(String),
    activities_ref_activity_code
        Nullable(String),
    activities_activity_name
        Nullable(String),
    activities_activity_kind
        Nullable(String),

    authorities_authority_code
        Nullable(String),
    authorities_authority_name
        Nullable(String),

    authorities_permissions_permission_code
        Nullable(String),
    authorities_permissions_permission_name
        Nullable(String),

    contacts_phone
        Nullable(String),
    contacts_site
        Nullable(String),
    contacts_mail
        Nullable(String),

    contracts_contract_number
        Nullable(String),
    contracts_sign_date
        Nullable(String),
    contracts_org_code_contract
        Nullable(String),
    contracts_org_name_contract
        Nullable(String),
    contracts_orgcontractbudgetcode
        Nullable(String),

    fo_accounts_fo_name
        Nullable(String),
    fo_accounts_fo_code
        Nullable(String),
    fo_accounts_account_type_name
        Nullable(String),
    fo_accounts_num
        Nullable(String),

    facial_accounts_srv_ufk_code
        Nullable(String),
    facial_accounts_ref_srv_ufk_code
        Nullable(String),
    facial_accounts_srv_ufk_name
        Nullable(String),
    facial_accounts_open_tofk_code
        Nullable(String),
    facial_accounts_open_tofk_name
        Nullable(String),
    facial_accounts_open_ufk_code
        Nullable(String),
    facial_accounts_ref_open_ufk_code
        Nullable(String),
    facial_accounts_open_ufk_name
        Nullable(String),
    facial_accounts_kind_name
        Nullable(String),
    facial_accounts_kind_code
        Nullable(String),
    facial_accounts_status
        Nullable(String),
    facial_accounts_num
        Nullable(String),
    facial_accounts_close_date
        Nullable(String),
    facial_accounts_create_date
        Nullable(String),
    facial_accounts_account_org_code
        Nullable(String),
    facial_accounts_account_org_full_name
        Nullable(String),
    facial_accounts_ppo_code
        Nullable(String),
    facial_accounts_ppo_name
        Nullable(String),

    heads_fio
        Nullable(String),
    heads_post
        Nullable(String),
    heads_head_main
        Nullable(String),
    heads_doc_name
        Nullable(String),
    heads_doc_num
        Nullable(String),
    heads_doc_date
        Nullable(String),

    ks_accounts_num
        Nullable(String),
    ks_accounts_open_date
        Nullable(String),
    ks_accounts_close_date
        Nullable(String),
    ks_accounts_open_tofk_code
        Nullable(String),
    ks_accounts_open_tofk_name
        Nullable(String),
    ks_accounts_ref_srv_ufk_code
        Nullable(String),
    ks_accounts_account_vid_name
        Nullable(String),
    ks_accounts_ppo_code
        Nullable(String),

    non_participant_permissions_code
        Nullable(String),
    non_participant_permissions_name
        Nullable(String),
    non_participant_permissions_start_date
        Nullable(String),
    non_participant_permissions_end_date
        Nullable(String),
    non_participant_permissions_auth_budg_code
        Nullable(String),
    non_participant_permissions_auth_budg_name
        Nullable(String),
    non_participant_permissions_auth_ppo_code
        Nullable(String),
    non_participant_permissions_auth_ppo_name
        Nullable(String),
    non_participant_permissions_auth_kbk_glava_code
        Nullable(String),
    non_participant_permissions_auth_kbk_glava_name
        Nullable(String),
    non_participant_permissions_registry_num
        Nullable(String),

    participant_permissions_code
        Nullable(String),
    participant_permissions_name
        Nullable(String),
    participant_permissions_start_date
        Nullable(String),
    participant_permissions_end_date
        Nullable(String),

    procurement_permissions_name
        Nullable(String),
    procurement_permissions_code
        Nullable(String),
    procurement_permissions_start_date
        Nullable(String),
    procurement_permissions_end_date
        Nullable(String),

    successions_parent_name
        Nullable(String),
    successions_parent_code
        Nullable(String),
    successions_ogrn
        Nullable(String),
    successions_doc_name
        Nullable(String),
    successions_number_doc
        Nullable(String),
    successions_document_date
        Nullable(String),
    successions_data_source
        Nullable(String),

    transf_auth_auth_fo_villages_ppo_name
        Nullable(String),
    transf_auth_auth_fo_villages_ppo_code
        Nullable(String),
    transf_auth_auth_fo_villages_code
        Nullable(String),
    transf_auth_auth_fo_villages_name
        Nullable(String),
    transf_auth_auth_fo_municipal_code
        Nullable(String),
    transf_auth_auth_fo_municipal_name
        Nullable(String),
    transf_auth_auth_reg_num
        Nullable(String),
    transf_auth_auth_start_date
        Nullable(String),
    transf_auth_auth_end_date
        Nullable(String),
    transf_auth_kbk_glava_code
        Nullable(String),
    transf_auth_budget_code
        Nullable(String),

    ubpfin_fin_doc_name
        Nullable(String),
    ubpfin_fin_doc_num
        Nullable(String),
    ubpfin_fin_doc_date
        Nullable(String),

    ubp_fin_fku_fku_doc_name
        Nullable(String),
    ubp_fin_fku_fku_doc_num
        Nullable(String),
    ubp_fin_fku_fku_doc_date
        Nullable(String),

    ubp_transf_auth_bp_ppo_name
        Nullable(String),
    ubp_transf_auth_bp_ppo_code
        Nullable(String),
    ubp_transf_auth_bp_bud_level_nsi_code
        Nullable(String),
    ubp_transf_auth_bp_bud_level_nsi_name
        Nullable(String),
    ubp_transf_auth_bp_budget_nsi_code
        Nullable(String),
    ubp_transf_auth_bp_budget_nsi_name
        Nullable(String),
    ubp_transf_auth_bp_code_bk
        Nullable(String),
    ubp_transf_auth_bp_head_name
        Nullable(String),

    ubp_transf_auth_bu_auth_bu_auth_org_code
        Nullable(String),
    ubp_transf_auth_bu_auth_bu_auth_name
        Nullable(String),
    ubp_transf_auth_bu_auth_bu_start_date
        Nullable(String),
    ubp_transf_auth_bu_auth_bu_end_date
        Nullable(String),

    updated_at
        DateTime64
)
    ENGINE = ReplacingMergeTree(updated_at) ORDER BY (info_guid);
